### ISSUE TITLE
Plugin is executed yet doesn't add anything to commits in GitLab

### ISSUE THREAD

**Issue by DvdGiessen** [gabrie-allaigre/sonar-gitlab-plugin#3] opened 2016-07-01 13:22 UTC
I seem to have some trouble getting this plugin set up correctly. I've added to plugin to SonarQube (currently 5.6, but I also tried with earlier versions), and set up all configuration for my project:
- Created a user in GitLab, which has developer access to the relevant projects.
- `sonar.gitlab.url`, `sonar.gitlab.user_token` and `sonar.gitlab.max_global_issues` set in SonarQube's global settings.
- `sonar.gitlab.project_id` is also set in SonarQube's project settings.

I'm running using the Sonar Scanner (2.6.1) in a GitLab CI build, as follows:

```
sonar-scanner -Dsonar.host.url=$SONAR_HOSTNAME -Dsonar.projectKey=$SONAR_PROJECT_KEY -Dsonar.projectName=$SONAR_PROJECT_NAME -Dsonar.projectVersion=$SONAR_PROJECT_VERSION  -Dsonar.sources=./ -Dsonar.exclusions=vendor/** -Dsonar.login=$SONAR_USERNAME -Dsonar.password=$SONAR_PASSWORD -Dsonar.php.tests.reportPath=./phpunit-report.tests.xml -Dsonar.php.coverage.reportPath=./phpunit-report.coverage.xml -Dsonar.branch=$CI_BUILD_REF_NAME -Dsonar.gitlab.project_id=$CI_PROJECT_ID -Dsonar.gitlab.commit_sha=$CI_BUILD_REF -Dsonar.gitlab.ref_name=$CI_BUILD_REF_NAME
```

The scanner runs without errors, the scan results appear in SonarQube and judging by the output the GitLab plugin is loaded and executed. (See http://pastebin.com/dySw8B2N for the output.)

However, the plugin doesn't seem to work: No comments are added in GitLab to any new commits.

I'm not sure if I'm missing something in my configuration, but as far as I can gather from the README I've set up everything correctly, and the output doesn't show any errors or other messages to point me in the direction of any solution.

**Comment by gabrie-allaigre** [comment] 2016-07-01 14:26
Hi,
have you a new issue ?
Add in mvn command -Dsonar.issuesReport.console.enable=true

**Comment by DvdGiessen** [comment] 2016-07-01 18:10
Setting `sonar.issuesReport.console.enable` doesn't generate a list of issues in the console; after searching for a bit it seems that the Issues Report plugin has been deprecated since SQ 5.1?

There were (multiple) new issues were introduced in that commit, and those new issues did show up in the SonarQube web interface. (I've tested with multiple commits, all with different kind of issues introduced. SonarQube picks them up, they just don't get commented on in GitLab.)

**Comment by gabrie-allaigre** [comment] 2016-07-01 20:00
GitLab plugin must a sonar preview mode only

**Comment by DvdGiessen** [comment] 2016-07-04 09:59
Ah, that was the issue! Running the scanner in preview mode (`-Dsonar.analysis.mode=preview`) resolved it.

Is this a inherent limitation of how Sonar Scanner operates? Right now I have to run the analysis twice, once for the GitLab-plugin to work and then directly again to also actually publish the results to SonarQube.

**Comment by pmsudhi** [comment] 2016-11-02 08:00
@DvdGiessen , i was also trying to achieve gitlab-sonarqube integration, but very beginner in the whole process. i was able to setup the sonar scanner on the machine where Gitlab CI is running. i added the build step as you done in the project, but fails with message 
`'sonar-scanner' is not recognized as an internal or external command`

iam able to run the command from command line from CI machine though

**Comment by rbosneag** [comment] 2016-11-25 11:41
In my case `sonar.analysis.mode=preview` didn't work either, tried also with `dryRun` true/false. 
I wonder why the GitLab plugin is tied to the `preview` option, why not allow to post in GitLab for full analysis as well?  

Regarding running the analysis twice, it looks like it's by design: http://www.sonarqube.org/analysis-vs-preview-vs-incremental-preview-in-sonarqube/ and it makes sense, but it would still be nice to have the comments in GitLab for full analysis. 

@gabrie-allaigre any news on this matter?

**Comment by laurre** [comment] 2016-12-16 15:56
I don't know if it will help but I was not seeing any comments neither. My solution was to:

* use the preview mode to launch the analysis, else it will not work
* as I had not activated the preview mode, the new issues were registered in my  Sonar server. So when I found that I needed to use the preview mode, the issues were not new, and no comment showed up in GitLab. So make sure that the issues are really new, and that Sonar does not know them at all.

To help troubleshoot the second problem, I had to clone this plugin, add debug traces in the console in various files and upload the modified version of the plugin to the Sonar server. This surely helps !

**Comment by gtrias** [comment] 2017-01-04 18:15
Nothing of the above has helped me in running this plugin successfully. I tried everything with no sucess. 

- The sonar-scanner runs well and reports no error. 
- The preview mode is enabled.
- The new issues are reported to sonarqube well.
- The sonarqube can post messages to gitlab since if I enable `GitLab Comment On No New Issue` option it sais there's no issues..

But no issue message in gitlab of any mistake in the code :(

**Comment by laurre** [comment] 2017-01-04 18:21
Something bugs me: if the preview mode is really enabled, new issues should NOT be reported to sonarqube.

**Comment by gtrias** [comment] 2017-01-04 18:27
Well I'm executing sonnar-scanner from go.cd ant the reported running command is:
```
19:23:22.271 [go] Start to execute task: <exec command="sh" >
<arg>-c</arg>
<arg>sonar-scanner</arg>
<arg>-Dsonar.issuesReport.console.enable=true</arg>
<arg>-Dsonar.gitlab.ref_name=master</arg>
<arg>-Dsonar.analysis.mode=preview</arg>
<arg>-Dsonar.gitlab.commit_sha=$GO_TO_REVISION</arg>
```

**Comment by laurre** [comment] 2017-01-04 23:15
The error seems quite clear, do you have any language plugin installed on your SonarQube server ?

**Comment by gtrias** [comment] 2017-01-04 23:44
I thought the same an it was the first thing to check with no success. I've tried to:

- reinstall javascript plugin in sonarqube server. 
- try to change language in sonar-project.properties from js to javascript
- set quality to the project in sonarqube server. 

Nothing has changed. But it seems weird to me that other scan types were able to find the proper plugins.

**Comment by n-b-sonar** [comment] 2017-01-17 08:02
Hi @gtrias ,

Have given some guidance on the [Google Group thread](https://groups.google.com/forum/#!topic/sonarqube/G77UKtXQUAo) where the same error was reported.

Long story short: double-check what's configured in your SonarQube Admin settings (General section), for the properties _Plugins accepted for Preview mode_ and _Plugins excluded for Preview mode_. These properties restrict the set of plugins seen by the scanner when executed in _preview_ mode, so it can likely explain why your preview analysis fails with _No language plugins are installed_ (e.g. if include/exclude properties hide all language plugins). Best is to leave the _include_ property blank, and review what you decide to exclude.

Keep us posted.

**Comment by gtrias** [comment] 2017-01-17 10:35
@n-b-sonar Thank you so much!! Was the "Plugins accepted for Preview mode", I didn't known there was an option to avoid the preview mode to fetch all the plugins. 
After removed the Plugins accepted it just works!!
Thanks again

**Comment by amilien** [comment] 2017-02-27 20:51
I want to understand better how this plugin works with Gitlab CI. My goal is to run this plugin on Gitlab MRs so it could make necessary comments there.
What I did so far:
1. Installed and ran locally Sonarqube with sonar-gitlab-plugin and java plugin for my android project.
2. Set up SonarQube's global and project settings.
I was able to launch full project sonar analysis by `./gradlew sonarqube`.
Now my question is how to launch the sonar analysis only for changes in MR? Is it just enough to add following in `.gitlab-ci.yml`?

`sh gradlew sonarqube -Psonar.analysis.mode=preview -Psonar.issuesReport.console.enable=true \
  -Psonar.gitlab.commit_sha=$CI_BUILD_REF -Psonar.gitlab.ref_name=$CI_BUILD_REF_NAME \
  -Psonar.gitlab.project_id=$CI_PROJECT_ID`

These variables - $CI_BUILD_REF, $CI_BUILD_REF_NAME, $CI_PROJECT_ID - will they be automatically resolved?

**Comment by laurre** [comment] 2017-02-28 14:44
These variables are predefined by GitLab and accessible from the .gitlab-ci.yml file. See here : https://docs.gitlab.com/ce/ci/variables/.

The only thing different in my script is the `-Psonar.gitlab.project_id=$CI_PROJECT_ID.`
I personally use `-Psonar.gitlab.project_id=projectGroup/projectName`. Which **seems** to be equivalent with `-Psonar.gitlab.project_id=$CI_PROJECT_PATH`.

**Comment by johnou** [comment] 2017-03-02 14:31
@amilien here is my .gitlab-ci.yml for sonarqube

```xml
sonarqube_preview:
  script:
    - mvn --batch-mode verify sonar:sonar -DskipITs -DskipTests -Dgpg.sign=false -Dsonar.host.url=https://xxx -Dsonar.gitlab.project_id=xxx/xxx -Dsonar.analysis.mode=preview -Dsonar.issuesReport.console.enable=true -Dsonar.gitlab.commit_sha=$CI_BUILD_REF -Dsonar.gitlab.ref_name=$CI_BUILD_REF_NAME
  stage: test
  except:
    - develop
    - master
    - /^hotfix_.*$/
    - /.*-hotfix$/
  tags:
    - java

sonarqube:
  script:
    - mvn --batch-mode verify sonar:sonar -DskipITs -DskipTests -Dgpg.sign=false -Dsonar.host.url=https://xxx -Dsonar.gitlab.project_id=xxx/xxx -Dsonar.gitlab.commit_sha=$CI_BUILD_REF -Dsonar.gitlab.ref_name=$CI_BUILD_REF_NAME
  stage: test
  only:
    - master
  tags:
    - java
```

**Comment by johnou** [comment] 2017-03-18 21:52
@DvdGiessen please try with 2.0.0-beta2 and report back.

**Comment by johnou** [comment] 2017-03-18 21:59
wow, just scrolled up and see your issue was actually resolved here https://github.com/gabrie-allaigre/sonar-gitlab-plugin/issues/3#issuecomment-230253471

@gabrie-allaigre should be good to close this issue.

**Comment by dinhkk** [comment] 2017-03-22 09:33
I used sonar-gitlab-plugin for php. The test project is sample project of sonarqube scanner.
Many thanks to @johnou 
The following configuration worked for me.
File sonar-project.properties:
```
sonar.projectKey=org.sonarqube:$CI_PROJECT_NAME
sonar.projectName=PHP :: ${CI_PROJECT_NAME}
sonar.projectVersion=1.0

sonar.language=php
sonar.sources=./
sonar.sourceEncoding=UTF-8
```

File .gitlab-ci.yml
```
sonarqube_preview:
  script:
    - sonar-scanner -Dgpg.sign=false -Dsonar.host.url=http://domain:9101 -Dsonar.gitlab.project_id=$CI_PROJECT_PATH -Dsonar.analysis.mode=preview -Dsonar.issuesReport.console.enable=true -Dsonar.gitlab.commit_sha=$CI_BUILD_REF -Dsonar.gitlab.ref_name=$CI_BUILD_REF_NAME
  stage: test

sonarqube:
  script:
    - sonar-scanner -Dgpg.sign=false -Dsonar.host.url=http://domain.com:9101
  stage: test
  only:
    - master
```

Result on gitlab:
![On gitlab](http://i.imgur.com/YRLjSZ1.png)
Result on sonarqube:
 ![On sonarqube](http://i.imgur.com/7ewIhFg.png)

**Comment by johnou** [comment] 2017-03-23 09:33
@dinhkk I think you can drop ```-Dgpg.sign=false```

**Comment by gabrie-allaigre** [comment] 2017-03-27 14:04
Good,

**Comment by ChanShuYi** [comment] 2017-04-21 07:53
It have some trouble in configure sonar-gitlab-plugin.

I want SonarQube to report the analysis result to gitlab, and I had done the following step:

- install sonar-gitlab-plugin in sonar
- configure gitlab server infomation in Administrator-General Setting.
- configure GitLab Project id in Project-Administrator Setting.
- setting in the .m2/setting.xml with following :

```
<pluginGroups>
        <pluginGroup>org.sonarsource.scanner.maven</pluginGroup>
</pluginGroups> 
.......
<profile>
        <id>sonar</id>
        <activation>
            <activeByDefault>true</activeByDefault>
        </activation>
        <properties>
            <!-- Optional URL to server. Default value is http://localhost:9000 -->
            <sonar.host.url>http://localhost:9000</sonar.host.url>
        </properties>
    </profile>
......
```

then I go into my maven project root directory(where pom.xml stay in), and use the following command:

```
mvn --batch-mode verify sonar:sonar -Dsonar.analysis.mode=preview -Dsonar.gitlab.commit_sha=649d921e8a029c86158c42d9bc40e47afaf055ac -Dsonar.gitlab.ref_name=master -Dsonar.gitlab.project_id=sonarqube_code
```

but the result tells me something is wrong :

```
[INFO] Plugin [l10nzh] defines 'l10nen' as base plugin. This metadata can be removed from manifest of l10n plugins since version 5.2.
[INFO] SonarQube version: 5.6.6
[INFO] Default locale: "en_US", source code encoding: "UTF-8"
[INFO] Process project properties
[INFO] Load project repositories
[INFO] Load project repositories (done) | time=228ms
[INFO] Execute project builders
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.222 s
[INFO] Finished at: 2017-04-21T00:49:19-07:00
[INFO] Final Memory: 49M/118M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.3.0.603:sonar (default-cli) on project code: Unable to load component class org.sonar.batch.scan.ImmutableProjectReactor: Unable found project for sonarqube_code Verify Configuration sonar.gitlab.project_id or sonar.gitlab.user_token access project -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

but when I run with `mvn --batch-mode verify sonar:sonar -Dsonar.analysis.mode=preview -Dsonar.gitlab.project_id=sonarqube_code`, the project compile SUCCESS. but no inline comment in Gitlab.

**Comment by gabrie-allaigre** [comment] 2017-04-21 08:08
Hi,
sonar.gitlab.project_id=sonarqube_code is wrong, Format is Project ID in GitLab or internal id or namespace + name or namespace + path or url http or ssh url or url or web.

For `mvn --batch-mode verify sonar:sonar -Dsonar.analysis.mode=preview -Dsonar.gitlab.project_id=sonarqube_code`, the project compile SUCESS because plugin is not enable, For enable plugin, `sonar.gitlab.commit_sha` is mandatory

**Comment by ChanShuYi** [comment] 2017-04-21 10:01
Thanks for your reply, I had been trying to solve this problem for several days.  @gabrie-allaigre 

Follow your reply, I change the value of `sonar.gitlab.project_id` into one of three value:

- code(it's my gitlab project name)
- git@gitlab.chenyurong.com:chenyurong/code.git
- http://chenyurong@gitlab.chenyurong.com/chenyurong/code.git

that means I run the following three command seprately:

```
mvn --batch-mode verify sonar:sonar -Dsonar.analysis.mode=preview -Dsonar.gitlab.commit_sha=649d921e8a029c86158c42d9bc40e47afaf055ac -Dsonar.gitlab.ref_name=master -Dsonar.gitlab.project_id=code

mvn --batch-mode verify sonar:sonar -Dsonar.analysis.mode=preview -Dsonar.gitlab.commit_sha=649d921e8a029c86158c42d9bc40e47afaf055ac -Dsonar.gitlab.ref_name=master -Dsonar.gitlab.project_id=git@gitlab.chenyurong.com:chenyurong/code.git

mvn --batch-mode verify sonar:sonar -Dsonar.analysis.mode=preview -Dsonar.gitlab.commit_sha=649d921e8a029c86158c42d9bc40e47afaf055ac -Dsonar.gitlab.ref_name=master -Dsonar.gitlab.project_id=http://chenyurong@gitlab.chenyurong.com/chenyurong/code.git
```

but they all turns the same error :

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.580 s
[INFO] Finished at: 2017-04-21T02:52:51-07:00
[INFO] Final Memory: 49M/118M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.3.0.603:sonar (default-cli) on project code: Unable to load component class org.sonar.batch.scan.ImmutableProjectReactor: Unable found project for http://chenyurong@gitlab.chenyurong.com/chenyurong/code.git Verify Configuration sonar.gitlab.project_id or sonar.gitlab.user_token access project -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
```

would you know what's wrong with the maven command.    thanks.

**Comment by gabrie-allaigre** [comment] 2017-04-21 10:10
try chenyurong/code
or http://gitlab.chenyurong.com/chenyurong/code.git

**Comment by gabrie-allaigre** [comment] 2017-04-21 10:18
Have you set access token in SonarQube ?

**Comment by ChanShuYi** [comment] 2017-04-21 10:29
what do you mean access token in SonarQube, in which menu ?

**Comment by gabrie-allaigre** [comment] 2017-04-21 10:33
In SonarQube Administration -> General Settings -> GitLab -> GitLab User Token

**Comment by ChanShuYi** [comment] 2017-04-21 10:38
Just now I add the `-Dsonar.gitlab.user_token` to previous maven command and it works.

```
mvn --batch-mode verify sonar:sonar -Dsonar.analysis.mode=preview -Dsonar.gitlab.commit_sha=649d921e8a029c86158c42d9bc40e47afaf055ac -Dsonar.gitlab.ref_name=master -Dsonar.gitlab.user_token=xgxpcGw-TzsRDmkFG-9S -Dsonar.gitlab.project_id=git@gitlab.chenyurong.com:chenyurong/code.git
```

the project compile SUCCESS.  But when I browse the SonarQube Web Page, the `code` project seems doesn't update according to the `LAST ANALYSIS` column. Is it because I use the `verify` in maven command ? 

by the way, I did set the GitLab User Token already in `SonarQube Administration -> General Settings -> GitLab -> GitLab User Token`.

**Comment by gabrie-allaigre** [comment] 2017-04-21 10:48
Sonar preview mode not change page in SonarQube.
In cmd, see
```
[INFO] ANALYSIS SUCCESSFUL
[INFO] Executing post-job GitLab Commit Issue Publisher
[INFO] Report status=success, desc=SonarQube reported no issues
```

**Comment by ChanShuYi** [comment] 2017-04-21 11:23
Thanks for your instruction, I really really appreciate that. Without your reply, maybe I can't solve this problem.

I can see the inline comment in gitlab now. Thanks again~~

**Comment by gabrie-allaigre** [comment] 2017-04-21 11:25
Good

**Closed by gabrie-allaigre** 2017-04-21 11:25 UTC

**Comment by JokerDevops** [comment] 2020-04-23 07:19
hi

**Comment by JokerDevops** [comment] 2020-04-23 07:25
Hi everyone, can this question be reopened? My problems:when I used `mvn --batch-mode verify sonar:sonar \
    -Dsonar.host.url=http://192.168.0.51:9000 \
    -Dsonar.login=admin \
    -Dsonar.password=admin \
    -Dsonar.analysis.mode=preview \
    -Dsonar.gitlab.project_id=$CI_PROJECT_ID \
    -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA \
    -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME
`He was successful. I saw sonarqube's detection information.But he reported an error when I used sonar-scanner.The project profile for sonar - scanner is as follows
```properties
sonar.projectKey=org.sonarqube:java-print-demo-scanner
sonar.projectName=Java :: print-demo :: SonarQube Scanner
sonar.projectVersion=1.0
sonar.sources=src
sonar.language=java
sonar.sourceEncoding=UTF-8
sonar.login=admin
sonar.password=admin
sonar.analysis.mode=preview
sonar.issuesReport.console.enable=true
sonar.gitlab.project_id=$CI_PROJECT_PATH
sonar.gitlab.commit_sha=$GIT_COMMIT
sonar.gitlab.ref_name=$GIT_BRANCH
```
The error message after executing sonar-scanner is as follows:
```
Caused by: Failed to execute project builder: com.talanlabs.sonar.plugins.gitlab.CommitProjectBuilder
Caused by: java.lang.IllegalStateException: Unable found project for $CI_PROJECT_PATH Verify Configuration sonar.gitlab.project_id or sonar.gitlab.user_token access project
```
I hope to get your help. Thank you
